# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PiAVI
email: gllmar.github.io
description: > # this means to ignore newlines until "baseurl:"
  Piavi est interactif
baseurl: "/piavi" # the subpath of your site, e.g. /blog
url: "http://gllmar.github.io/" # the base hostname & protocol for your site
twitter_username: arsenog
github_username:  gllmar

# Build settings
markdown: kramdown
